chat:
  local:
    radius: 25.0
    discord-channel-id: 000000000000000000
  global:
    discord-channel-id: 000000000000000000
resource-pack:
  full:
    hash:
    dropbox-url:
    yandex-disk:
  lite:
    hash:
    dropbox-url:
    yandex-disk-url: