chat:
  local:
    radius: 25.0
    discord-channel-id: 0
  global:
    discord-channel-id: 0
resource-pack:
  full:
    hash:
    dropbox-url:
    yandex-disk-url:
  lite:
    hash:
    dropbox-url:
    yandex-disk-url:
