language: ru-ru
date-format: "EEE, yyyy-MM-dd HH:mm z"
plugin-hooks:
  msdecor:
    enabled: true
    ignore-version-check: false
  msblock:
    enabled: true
    ignore-version-check: false
  discordsrv:
    enabled: true
    ignore-version-check: false
  authme:
    enabled: true
    ignore-version-check: false
  protocollib:
    ignore-version-check: false
chat:
  join:
    enabled: true
    permissions: [ default ]
    prefix: ""
    colors:
      primary: "#FFEE93"
      secondary: "#FCF5C7"
    discord:
      enabled: true
      discord-channel-id: [ 000000000000000000 ]
  quit:
    enabled: true
    permissions: [ default ]
    prefix: ""
    colors:
      primary: "#FFEE93"
      secondary: "#FCF5C7"
    discord:
      enabled: true
      discord-channel-id: [ 000000000000000000 ]
  death:
    enabled: true
    permissions: [ default ]
    prefix: ""
    colors:
      primary: "#FFEE93"
      secondary: "#FCF5C7"
    discord:
      enabled: true
      discord-channel-id: [ 000000000000000000 ]
  private-messages:
    enabled: true
    permissions: [ default ]
    prefix: " ꀕ "
    colors:
      primary: "#FFEE93"
      secondary: "#FCF5C7"
    discord:
      enabled: true
      discord-channel-id: [ 000000000000000000 ]
  actions:
    enabled: true
    radius: 25.0
    permissions: [ default ]
    enable-chat-symbols: true
    prefix: " ꀓ "
    show-messages-above-head: false
    colors:
      primary: "#FFAA00"
      secondary: "#FFC369"
    discord:
      enabled: true
      discord-channel-id: [ 000000000000000000 ]
  local:
    enabled: true
    radius: 25.0
    permissions: [ default ]
    prefix: ""
    show-messages-above-head: true
    colors:
      primary: "#ABA494"
      secondary: "#F1F0E3"
    discord:
      enabled: true
      discord-channel-id: [ 000000000000000000 ]
  global:
    enabled: true
    permissions: [ default ]
    prefix: "[WM] "
    show-messages-above-head: false
    symbol: '!'
    colors:
      primary: "#ABA494"
      secondary: "#F1F0E3"
    discord:
      enabled: true
      discord-channel-id: [ 000000000000000000 ]
resource-packs:
  enabled: true
  full:
    hash:
    dropbox-url:
    yandex-disk-url:
  lite:
    hash:
    dropbox-url:
    yandex-disk-url:
registration-process:
  music: "music_disc.far"
  name-regex: "[-А-яҐґІіЇїЁё]+"