plugin-hooks:
  msdecor:
    enable: true
  msblock:
    enable: true
  discordsrv:
    enable: true
  authme:
    enable: true
chat:
  local:
    radius: 25.0
    send-messages-to-discord: true
    discord-channel-id: 000000000000000000
  global:
    send-messages-to-discord: true
    discord-channel-id: 000000000000000000
resource-pack:
  full:
    hash:
    dropbox-url:
    yandex-disk:
  lite:
    hash:
    dropbox-url:
    yandex-disk-url: