name: ${name}
version: ${version}
description: ${description}
authors: [${authors}]
website: ${url}

main: ${mainClass}
api-version: ${apiVersion}
softdepend:
  - AuthMe
  - ProtocolLib
  - DiscordSRV
  - msDecor
  - msBlock

commands:
  me:
    usage: ' ꀑ §cИспользуй: /<command> [действие]'
    description: Проигрывает действие в чате в заданом радиусе
  todo:
    usage: ' ꀑ §cИспользуй: /<command> [речь] * [действие]'
    description: Проигрывает, в заданом радиусе, действие и речь в чате
  try:
    usage: ' ꀑ §cИспользуй: /<command> [действие]'
    description: Рандомно определяет исход действия и проигрывает его в заданом радиусе
  spit:
    usage: ' ꀑ §cИспользуй: /<command>'
    description: Покажи свою дерзость и плюнь кому то в ебло
  fart:
    usage: ' ꀑ §cИспользуй: /<command>'
    description: Пердани вкусно на публику
  sit:
    usage: ' ꀑ §cИспользуй: /<command>'
    aliases: [ sit, s ]
    description: Сядь на картаны и порви жопу
  mute:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [время] [причина]'
    permission: msUtils.mute
    description: Замутить игрока
  privatemessage:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [сообщение]'
    aliases: [ privatemessage, pm, w, tell, msg ]
    description: Отправь другому игроку приватное сообщение
  unmute:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname]'
    permission: msUtils.mute
    description: Размутить игрока
  ban:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [время] [причина]'
    permission: msUtils.ban
    description: Забанить игрока
  unban:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname]'
    permission: msUtils.ban
    description: Разбанить игрока
  kick:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [причина]'
    permission: msUtils.kick
    description: Кикнуть игрока
  getmaploc:
    usage: ' ꀑ §cИспользуй: /<command>'
    permission: msUtils.mapLocation
    description: Добывает координаты карты находящейся в руке
  resourcepack:
    usage: ' ꀑ §cИспользуй: /<command>'
    aliases: [ resourcepack, rp ]
    description: Открывает меню с ресурспаками
  info:
    usage: ' ꀑ §cИспользуй: /<command> [ID]'
    permission: msUtils.info
    description: Выводит в чат информацию про игрока
  crafts:
    usage: ' ꀑ §cИспользуй: /<command>'
    aliases: [ crafts, recipes ]
    description: Открывает меню с крафтами кастомных предметов/декора/блоков
  whitelist:
    usage: ' ꀑ §cИспользуй: /<command> [add/remove/reload] [ID/Nickname]'
    permission: msUtils.whitelist
    description: Удаляет/добавляет игрока в вайтлист
  teleporttolastdeathlocation:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname]'
    aliases: [ teleporttolastdeathlocation, teleporttolastdeathloc, tptolastdeathlocation, tptolastdeathloc, tptolastdeath ]
    permission: msUtils.teleporttolastdeathlocation
    description: Телепортирует игрока на его последнее место смерти
  worldteleport:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [world name] [x] [y] [z]'
    aliases: [ worldteleport, worldtp, wtp, teleportworld, tpworld, tpw ]
    permission: msUtils.worldteleport
    description: Телепортирует игрока на координаты в указаном мире

permissions:
  msUtils.info:
    default: op
  msUtils.ban:
    default: op
  msUtils.mute:
    default: op
  msUtils.kick:
    default: op
  msUtils.mapLocation:
    default: op
  msUtils.whitelist:
    default: op
  msUtils.teleporttolastdeathlocation:
    default: op
  msUtils.worldteleport:
    default: op