name: ${name}
version: ${version}
description: ${description}
authors: ${authors}
website: ${url}

main: ${mainClass}
api-version: ${apiVersion}
softdepend:
  - msCore
  - AuthMe
  - ProtocolLib
  - DiscordSRV
